"""Shared limits for model-facing LSP payloads."""

MAX_LSP_ITEMS = 500
DEFAULT_MAX_DIAGNOSTICS = 100
DEFAULT_MAX_SYMBOLS = 200
DEFAULT_MAX_DEFINITIONS = 20
DEFAULT_MAX_REFERENCES = 100
MAX_LSP_MESSAGE_CHARS = 500
MAX_LSP_NAME_CHARS = 200
