'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {compileHookContributions}=require('../../../services/plugins/hooks/contribution-compiler');
const {HookDispatcher}=require('../../../services/plugins/hooks/dispatcher');
const {HookOutboxStore}=require('../../../services/plugins/hooks/outbox-store');
const {createMemoryFsFacade}=require('../../../services/plugins/store/fs-facade');
const {readJsonFile}=require('../../../services/plugins/store/json-file-io');
const d=(x)=>x.repeat(64);const authority={active_generation_id:'gen-1',commit_epoch:1};
function descriptor(){return {hook_schema_version:6,publisher_id:'acme',plugin_id:'plug',contribution_id:'hook',binding_digest:d('1'),artifact_digest:d('2'),executable_digest:d('3'),active_generation_id:'gen-1',commit_epoch:1,event:'plugin.enabled',subject_scope:'self',max_depth:1,fanout:1,deadline_ms:100,replay_safe:false};}
function outbox(){return new HookOutboxStore({facade:createMemoryFsFacade(),baseDir:'plugins'});}
test('hook compilation isolates invalid rows and dispatcher is self-only/deduplicated',async()=>{const compiled=compileHookContributions([{bad:true},descriptor()],authority);assert.equal(compiled.accepted.length,1);const calls=[];const dispatcher=new HookDispatcher({descriptors:()=>compiled.accepted,currentAuthority:async()=>authority,outbox:outbox(),invoke:async(x)=>{calls.push(x);return {ok:true};}});const event={event_id:'event-1',event:'plugin.enabled',publisher_id:'acme',plugin_id:'plug',causal_depth:1};assert.equal((await dispatcher.enqueue(event)).ok,true);assert.equal((await dispatcher.enqueue(event)).duplicate,true);await dispatcher.idle();assert.equal(calls.length,1);assert.deepEqual(calls[0].forbidden,['lifecycle','consent','secret','spawn','hook_emit']);});
test('oversize/depth and queue pressure fail closed',async()=>{const dispatcher=new HookDispatcher({descriptors:()=>[],currentAuthority:async()=>authority,outbox:outbox(),invoke:async()=>{},maximumQueue:1});assert.equal((await dispatcher.enqueue({causal_depth:2})).reason,'hook_event_rejected');assert.equal((await dispatcher.enqueue({causal_depth:1,payload:'x'.repeat(70000)})).reason,'hook_event_rejected');});
test('ambiguous hooks never retry and replay-safe definitely-undispatched failures retry once',async()=>{const safe={...descriptor(),replay_safe:true};let calls=0;const dispatcher=new HookDispatcher({descriptors:()=>[safe],currentAuthority:async()=>authority,outbox:outbox(),invoke:async()=>{calls+=1;return calls===1?{ok:false,dispatched:false,reason:'not_dispatched'}:{ok:true};}});await dispatcher.enqueue({event_id:'event-retry',event:'plugin.enabled',publisher_id:'acme',plugin_id:'plug',causal_depth:1});await dispatcher.idle();assert.equal(calls,2);});
test('restart settles an ambiguous durable pending hook without replay',async()=>{const store=outbox();await store.putPending({event_id:'interrupted',event:'plugin.enabled',publisher_id:'acme',plugin_id:'plug',causal_depth:1});let calls=0;const dispatcher=new HookDispatcher({descriptors:()=>[descriptor()],currentAuthority:async()=>authority,outbox:store,invoke:async()=>{calls+=1;return {ok:true};}});assert.equal((await dispatcher.enqueue({event_id:'fresh',event:'plugin.enabled',publisher_id:'acme',plugin_id:'plug',causal_depth:1})).ok,true);await dispatcher.idle();assert.equal(calls,1);});
test('policy drift rejects queued hooks and revokeAll settles later valid events independently',async()=>{let revision=1;let release;const facade=createMemoryFsFacade();const store=new HookOutboxStore({facade,baseDir:'plugins'});const dispatcher=new HookDispatcher({descriptors:()=>[descriptor()],currentAuthority:async()=>authority,outbox:store,captureAuthority:()=>({revision}),guardAuthority:(token)=>token.revision===revision?{ok:true}:{ok:false,reason:'managed_policy_authority_stale'},invoke:()=>new Promise((resolve)=>{release=resolve;})});assert.equal((await dispatcher.enqueue({event_id:'running',event:'plugin.enabled',publisher_id:'acme',plugin_id:'plug',causal_depth:1})).ok,true);while(!release) await new Promise((resolve)=>setImmediate(resolve));assert.equal((await dispatcher.enqueue({event_id:'queued',event:'plugin.enabled',publisher_id:'acme',plugin_id:'plug',causal_depth:1})).ok,true);revision=2;const revoked=await dispatcher.revokeAll();assert.equal(revoked.rejected_count,1);release({ok:true});await dispatcher.idle();const state=await readJsonFile(facade,'plugins/runtime/hook-outbox-v6.json');const queued=state.value.receipts.find((item)=>item.event_id==='queued');assert.equal(queued.status,'failed');assert.equal(queued.reason,'managed_policy_revoked');});
test('enqueue disposal races cannot repopulate the queue or leave a pending receipt',async()=>{let releaseRecovery;let puts=0;const recovery=new Promise((resolve)=>{releaseRecovery=resolve;});const recoveryStore={settleInterruptedPending:()=>recovery,putPending:async()=>{puts+=1;return {ok:true};},settle:async()=>({ok:true})};const recoveryDispatcher=new HookDispatcher({descriptors:()=>[],currentAuthority:async()=>authority,outbox:recoveryStore,invoke:async()=>({ok:true})});const recovering=recoveryDispatcher.enqueue({event_id:'late-recovery',causal_depth:1});await recoveryDispatcher.dispose();releaseRecovery({ok:true});assert.deepEqual(await recovering,{ok:false,reason:'hook_dispatcher_disposed'});assert.equal(puts,0);assert.equal(recoveryDispatcher._queue.length,0);let releasePut;const settlements=[];const pendingStore={settleInterruptedPending:async()=>({ok:true}),putPending:()=>new Promise((resolve)=>{releasePut=resolve;}),settle:async(...args)=>{settlements.push(args);return {ok:true};}};const pendingDispatcher=new HookDispatcher({descriptors:()=>[],currentAuthority:async()=>authority,outbox:pendingStore,invoke:async()=>({ok:true})});const pending=pendingDispatcher.enqueue({event_id:'late-pending',causal_depth:1});while(!releasePut)await new Promise((resolve)=>setImmediate(resolve));await pendingDispatcher.dispose();releasePut({ok:true});assert.deepEqual(await pending,{ok:false,reason:'hook_dispatcher_disposed'});assert.deepEqual(settlements,[['late-pending','failed',0,'hook_dispatcher_disposed']]);assert.equal(pendingDispatcher._queue.length,0);});
test('policy revocation stops later matching hook descriptors',async()=>{let revision=1;const calls=[];const descriptors=['first','second'].map((contribution_id)=>({...descriptor(),contribution_id}));const dispatcher=new HookDispatcher({descriptors:()=>descriptors,currentAuthority:async()=>authority,outbox:outbox(),captureAuthority:()=>({revision}),guardAuthority:(token)=>token.revision===revision?{ok:true}:{ok:false},invoke:async({descriptor:item})=>{calls.push(item.contribution_id);revision=2;return {ok:true};}});await dispatcher.enqueue({event_id:'revoked-between-hooks',event:'plugin.enabled',publisher_id:'acme',plugin_id:'plug',causal_depth:1});await dispatcher.idle();assert.deepEqual(calls,['first']);});
