'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const { SecretValueDelivery,sourceFingerprint }=require('../../../services/plugins/full-host/secret-value-delivery');
const { SecretDeliveryGrantStore }=require('../../../services/plugins/full-host/secret-delivery-grant-store');
const { createMemoryFsFacade }=require('../../../services/plugins/store/fs-facade');
const digest='a'.repeat(64); const secret='synthetic-secret'; let now=Date.parse('2026-08-09T00:00:00Z');
function grant(){return {grant_schema_version:6,grant_id:'grant-1',approval_id:'approve-1',publisher_id:'acme',plugin_id:'plug',contribution_id:'host',active_generation_id:'gen-1',commit_epoch:1,session_id:'session-1',session_epoch:1,purpose:'secret_value_delivery',source_id_digest:digest,source_fingerprint:sourceFingerprint(secret),destination_digest:'b'.repeat(64),issued_at:'2026-08-09T00:00:00Z',expires_at:'2026-08-09T00:00:20Z',one_shot:true,spent:false};}
test('secret grant spends durably before delivery and cannot replay after ambiguous response',async()=>{let killed=false;const facade=createMemoryFsFacade();const grantStore=new SecretDeliveryGrantStore({facade,baseDir:'plugins',now:()=>now});const delivery=new SecretValueDelivery({secureStore:{getPluginFullHostSecret:async()=>secret},grantStore,deliver:async()=>{throw new Error('lost')},terminateSession:async()=>{killed=true},now:()=>now});assert.equal((await delivery.prepare(grant())).ok,true);const binding={session_id:'session-1',session_epoch:1,active_generation_id:'gen-1',commit_epoch:1};assert.equal((await delivery.consumeAndDeliver({grantId:'grant-1',binding})).reason,'secret_delivery_ambiguous');assert.equal(killed,true);const restarted=new SecretValueDelivery({secureStore:{getPluginFullHostSecret:async()=>secret},grantStore:new SecretDeliveryGrantStore({facade,baseDir:'plugins',now:()=>now}),deliver:async()=>({ok:true}),now:()=>now});assert.equal((await restarted.consumeAndDeliver({grantId:'grant-1',binding})).reason,'secret_grant_spent_or_missing');});
test('policy drift fences secret bytes across each asynchronous boundary and revokeAll spends leftovers',async()=>{let revision=1;let release;let delivered=false;const facade=createMemoryFsFacade();const grantStore=new SecretDeliveryGrantStore({facade,baseDir:'plugins',now:()=>now});const delivery=new SecretValueDelivery({secureStore:{getPluginFullHostSecret:()=>new Promise((resolve)=>{release=()=>resolve(secret);})},grantStore,deliver:async()=>{delivered=true;return {ok:true,receipt_id:'receipt'};},now:()=>now,captureAuthority:()=>({revision}),guardAuthority:(token)=>token.revision===revision?{ok:true}:{ok:false,reason:'managed_policy_authority_stale'}});assert.equal((await delivery.prepare(grant())).ok,true);const binding={session_id:'session-1',session_epoch:1,active_generation_id:'gen-1',commit_epoch:1};const pending=delivery.consumeAndDeliver({grantId:'grant-1',binding});while(!release) await new Promise((resolve)=>setImmediate(resolve));revision=2;release();assert.equal((await pending).reason,'managed_policy_authority_stale');assert.equal(delivered,false);const next={...grant(),grant_id:'grant-2'};assert.equal((await delivery.prepare(next)).ok,true);assert.equal((await delivery.revokeAll()).ok,true);assert.equal((await grantStore.spend('grant-2',binding)).reason,'secret_grant_spent_or_missing');});
