'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {compileEngineAdapters}=require('../../../services/plugins/engine-adapter/contribution-compiler');
const {EngineAdapterStreamBroker}=require('../../../services/plugins/engine-adapter/stream-broker');
const d=(x)=>x.repeat(64);const authority={active_generation_id:'gen-1',commit_epoch:1};
function descriptor(){return {adapter_schema_version:6,publisher_id:'acme',plugin_id:'plug',contribution_id:'engine',adapter_id:'research',binding_digest:d('1'),artifact_digest:d('2'),executable_digest:d('3'),active_generation_id:'gen-1',commit_epoch:1,supports_streaming:true,supports_cancellation:true,max_input_bytes:1024,max_stream_bytes:4096};}
test('compiler binds authority and stream broker enforces order and one terminal',async()=>{assert.equal(compileEngineAdapters([descriptor()],authority).accepted.length,1);const broker=new EngineAdapterStreamBroker({invokeHost:async()=>({frames:[{sequence:0,kind:'text',text:'hi'},{sequence:1,kind:'done'}]})});const result=await broker.start({requestId:'r',descriptor:descriptor(),authority,input:{prompt:'x'}});assert.equal(result.ok,true);assert.equal(result.terminal,true);assert.equal((await broker.acknowledge({requestId:'r',sequence:2})).reason,'engine_stream_not_active');});
test('out-of-order frames cancel fail closed',async()=>{const calls=[];const broker=new EngineAdapterStreamBroker({invokeHost:async(x)=>{calls.push(x.operation);return x.operation==='cancel'?{ok:true}:{frames:[{sequence:2,kind:'done'}]};}});assert.equal((await broker.start({requestId:'r',descriptor:descriptor(),authority,input:{}})).reason,'engine_stream_frame_rejected');assert.deepEqual(calls,['start','cancel']);});
test('active stream limit and host deadline fail closed',async()=>{let release;const broker=new EngineAdapterStreamBroker({maxActive:1,stepTimeoutMs:10,invokeHost:(x)=>x.operation==='cancel'?Promise.resolve({ok:true}):new Promise((resolve)=>{release=resolve;})});const first=broker.start({requestId:'first',descriptor:descriptor(),authority,input:{}});assert.equal((await broker.start({requestId:'second',descriptor:descriptor(),authority,input:{}})).reason,'engine_stream_limit');assert.equal((await first).reason,'engine_stream_host_failed');release?.({frames:[]});});
test('a hung cancellation is bounded after frame rejection',async()=>{const broker=new EngineAdapterStreamBroker({cancelTimeoutMs:10,invokeHost:(request)=>request.operation==='cancel'?new Promise(()=>{}):Promise.resolve({frames:[{sequence:2,kind:'done'}]})});assert.equal((await broker.start({requestId:'hung-cancel',descriptor:descriptor(),authority,input:{}})).reason,'engine_stream_frame_rejected');});
test('policy drift cancels a live stream with its descriptor and rejects stale frames',async()=>{let revision=1;let release;const calls=[];const broker=new EngineAdapterStreamBroker({captureAuthority:()=>({revision}),guardAuthority:(token)=>token.revision===revision?{ok:true}:{ok:false,reason:'managed_policy_authority_stale'},invokeHost:(request)=>{calls.push(request);return request.operation==='cancel'?Promise.resolve({ok:true}):new Promise((resolve)=>{release=resolve;});}});const pending=broker.start({requestId:'policy-race',descriptor:descriptor(),authority,input:{}});revision=2;release({frames:[{sequence:0,kind:'done'}]});assert.equal((await pending).reason,'managed_policy_authority_stale');const cancelled=calls.find((item)=>item.operation==='cancel');assert.equal(cancelled.descriptor.adapter_id,'research');});
test('generation drift cancels a live stream before acknowledgement can invoke its old host',async()=>{let current=authority;const calls=[];const broker=new EngineAdapterStreamBroker({guardRuntimeAuthority:(candidate)=>candidate===current?{ok:true}:{ok:false,reason:'privileged_authority_stale'},invokeHost:async(request)=>{calls.push(request.operation);return {frames:[]};}});assert.equal((await broker.start({requestId:'generation-race',descriptor:descriptor(),authority,input:{}})).ok,true);current={...authority,active_generation_id:'gen-2'};assert.equal((await broker.acknowledge({requestId:'generation-race',sequence:0})).reason,'privileged_authority_stale');assert.deepEqual(calls,['start','cancel']);assert.equal((await broker.acknowledge({requestId:'generation-race',sequence:0})).reason,'engine_stream_not_active');});
