"""Generate the cross-runtime plugin-platform contract validators.

Reads the closed-vocabulary descriptor schemas under config/plugins/v1/ through
config/plugins/v6/ plus independently versioned extension families,
lints them against the supported facet subset, resolves $defs references
and named string formats at generation time, and emits two interpreters
(JS + Python) that share one embedded SPEC and one validation algorithm so
a fix lands in both runtimes at once.

Regen: python scripts/generate_plugin_contracts.py
Check: python scripts/generate_plugin_contracts.py --check
"""

# Embedded JS/Python templates intentionally preserve generated-runtime layout.
# ruff: noqa: E501

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# Twin JS/Python interpreter templates live in a sibling module so this file
# (descriptor lint + schema resolution + CLI orchestration) stays under the
# shared 600-raw-line ratchet. SAFE_INTEGER_MIN/MAX must match the constants
# baked into scripts/generate_plugin_contracts_emitters.py (covered by the
# --check regeneration gate, so drift here fails closed rather than silently).
from scripts.generate_plugin_contracts_emitters import js_source, python_source  # noqa: E402

SCHEMA_DIRS = (
    ROOT / "config" / "plugins" / "v1",
    ROOT / "config" / "plugins" / "v2",
    ROOT / "config" / "plugins" / "v3",
    ROOT / "config" / "plugins" / "v4",
    ROOT / "config" / "plugins" / "v5",
    ROOT / "config" / "plugins" / "v6",
    ROOT / "config" / "plugins" / "extensions" / "session-provider-v1",
)
# Backward-compatible V1 seam retained for the frozen V1 generator harness.
SCHEMA_DIR = SCHEMA_DIRS[0]
JS_PATH = ROOT / "services" / "plugins" / "contracts" / "generated-plugin-contracts.js"
PY_PATH = ROOT / "sidecar" / "ai" / "plugins" / "generated_plugin_contracts.py"

COMMON_FILE = "_common.schema.json"

# Contract files are DISCOVERED, not listed. Parallel authoring lanes each add
# their own config/plugins/v1/<name>.schema.json without touching this module,
# so a wave of concurrent lanes never collides on a shared registry list.
# Sorted by filename so emission order — and therefore the generated bytes — is
# deterministic regardless of filesystem enumeration order.
def contract_files(schema_dir: Path = SCHEMA_DIR) -> list[str]:
    return sorted(p.name for p in schema_dir.glob("*.schema.json") if p.name != COMMON_FILE)

# --- Closed descriptor vocabulary ------------------------------------------------

ALLOWED_TYPES = {"object", "array", "string", "integer", "boolean", "enum", "const", "ref", "tagged_union"}
ALLOWED_ADDITIONAL_PROPERTIES = {"reject", "ignore", "preserve"}
SAFE_INTEGER_MIN = -9007199254740991
SAFE_INTEGER_MAX = 9007199254740991

# Named string formats. Generation-time resolution bakes the pattern/byte cap/
# NFC-check policy directly into each resolved string node, so neither runtime
# interpreter needs a "format" lookup table at validation time.
# Patterns use explicit [0-9] rather than \d. Python's re treats \d as ALL
# Unicode decimal digits while JavaScript's RegExp (without the u flag) treats
# it as ASCII [0-9] only, so a \d here would make the two generated runtimes
# disagree -- Python accepting Arabic-Indic "٢٠٢٤-..." timestamps that JS
# rejects. _lint_pattern rejects the shorthand classes outright so this cannot
# regress. Same reasoning applies to \w, \s and \b.
FORMATS: dict[str, dict[str, Any]] = {
    "sha256_hex": {"pattern": r"^[0-9a-f]{64}$", "max_utf8_bytes": 64, "nfc_check": False},
    "iso8601_utc": {"pattern": r"^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,6})?Z$", "max_utf8_bytes": 40, "nfc_check": False},
    "display_string": {"pattern": r"^[^\x00-\x1F\x7F-\x9F]+$", "max_utf8_bytes": 120, "nfc_check": True},
    "nfc_identifier": {"pattern": r"^[a-z][a-z0-9_-]{0,63}$", "max_utf8_bytes": 64, "nfc_check": True},
    "semver": {"pattern": r"^[0-9]{1,5}\.[0-9]{1,5}\.[0-9]{1,5}(-[0-9A-Za-z.-]{1,32})?(\+[0-9A-Za-z.-]{1,32})?$", "max_utf8_bytes": 80, "nfc_check": False},
    "publisher_id": {"pattern": r"^[a-z][a-z0-9-]{0,63}$", "max_utf8_bytes": 64, "nfc_check": True},
    "plugin_id": {"pattern": r"^[a-z][a-z0-9_-]{0,63}$", "max_utf8_bytes": 64, "nfc_check": True},
    "contribution_id": {"pattern": r"^[a-z][a-z0-9_-]{0,63}$", "max_utf8_bytes": 64, "nfc_check": True},
    "operation_id": {"pattern": r"^[a-z0-9][a-z0-9_-]{0,63}$", "max_utf8_bytes": 64, "nfc_check": True},
    "generation_id": {"pattern": r"^[a-z0-9][a-z0-9_-]{0,63}$", "max_utf8_bytes": 64, "nfc_check": True},
}
ALLOWED_FORMATS = set(FORMATS.keys())

# Validator-internal error codes: short snake_case identifiers, never CMP-* wire
# codes. The reason text lives once, here, so both generated runtimes emit
# byte-identical diagnostics without hand-syncing prose in two languages.
ERROR_REASONS: dict[str, str] = {
    "unknown_contract": "the requested contract name is not registered",
    "not_object": "value must be a JSON object",
    "not_array": "value must be a JSON array",
    "not_string": "value must be a string",
    "not_integer": "value must be an integer",
    "not_boolean": "value must be a boolean",
    "integer_is_bool": "boolean values are not accepted as integers",
    "integer_out_of_range": "integer is outside the allowed range",
    "invalid_unicode_scalar": "value contains an unpaired Unicode surrogate",
    "missing_required_field": "a required field is missing",
    "unknown_field": "an unexpected field was rejected by additional_properties",
    "max_keys_exceeded": "object has more keys than the schema allows",
    "max_items_exceeded": "array has more items than the schema allows",
    "unique_by_violation": "array items are not unique on the required key",
    "pattern_mismatch": "value does not match the required pattern",
    "max_bytes_exceeded": "value exceeds the maximum UTF-8 byte length",
    "forbidden_codepoint": "value contains a control, bidi-override, or zero-width code point",
    "not_nfc_normalized": "value is not in Unicode NFC normalization form",
    "enum_invalid": "value is not one of the allowed enum members",
    "const_mismatch": "value does not equal the required constant",
    "tagged_union_missing_tag": "tagged union is missing its discriminator tag field",
    "tagged_union_unknown_tag": "tagged union discriminator tag is not a known variant",
    "depth_budget_exceeded": "payload exceeds the maximum nesting depth",
    "node_budget_exceeded": "payload exceeds the maximum total node count",
    "key_budget_exceeded": "object exceeds the maximum key count structural budget",
    "array_budget_exceeded": "array exceeds the maximum item count structural budget",
    "nonfinite_number": "payload contains a non-finite number",
    "unsupported_value_type": "payload contains a value of an unsupported JSON type",
    "cycle_detected": "payload contains a cyclic reference",
    "payload_byte_budget_exceeded": "payload exceeds the maximum total UTF-8 byte size",
}

_LOOKAROUND_TOKENS = ("(?=", "(?!", "(?<=", "(?<!")
_BACKREFERENCE_RE = re.compile(r"\\[1-9]")
# Shorthand classes whose membership differs between Python's Unicode-aware re
# and JavaScript's ASCII-only RegExp. Spelling the class out keeps the two
# generated runtimes byte-identical on the same input.
_UNICODE_AMBIGUOUS_CLASSES = ("\\d", "\\D", "\\w", "\\W", "\\s", "\\S", "\\b", "\\B")
# unique_by keys are compared as a compact JSON array. Restricting the fields to
# scalars keeps that encoding byte-identical across the two runtimes (nested
# objects would depend on each language's key ordering).
_UNIQUE_BY_SCALAR_TYPES = {"string", "enum", "integer", "const", "boolean"}


class SchemaLintError(ValueError):
    """Raised when a schema file uses a facet outside the closed descriptor subset."""


def _check_facets(node: dict[str, Any], allowed: set[str], where: str, kind: str) -> None:
    extra = set(node.keys()) - allowed
    if extra:
        raise SchemaLintError(f"{where}: unsupported {kind} facet(s) {sorted(extra)}")


def _lint_pattern(pattern: str, where: str) -> None:
    if not isinstance(pattern, str) or not pattern:
        raise SchemaLintError(f"{where}: pattern must be a non-empty string")
    if not (pattern.startswith("^") and pattern.endswith("$")):
        raise SchemaLintError(f"{where}: pattern must be anchored with ^ and $")
    if "(?P<" in pattern or re.search(r"\(\?<[A-Za-z_]", pattern):
        raise SchemaLintError(f"{where}: named groups are not permitted in patterns")
    if any(token in pattern for token in _LOOKAROUND_TOKENS):
        raise SchemaLintError(f"{where}: lookaround is not permitted in patterns")
    if _BACKREFERENCE_RE.search(pattern):
        raise SchemaLintError(f"{where}: backreferences are not permitted in patterns")
    ambiguous = sorted({token for token in _UNICODE_AMBIGUOUS_CLASSES if token in pattern})
    if ambiguous:
        raise SchemaLintError(
            f"{where}: shorthand class(es) {ambiguous} match different characters in Python and "
            f"JavaScript; spell the set out explicitly (e.g. [0-9] instead of \\d)"
        )
    try:
        re.compile(pattern)
    except re.error as exc:
        raise SchemaLintError(f"{where}: pattern does not compile: {exc}") from exc


def _lint_integer_bound(value: Any, where: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise SchemaLintError(f"{where}: integer bound must be a plain integer")
    if value < SAFE_INTEGER_MIN or value > SAFE_INTEGER_MAX:
        raise SchemaLintError(f"{where}: integer bound is outside the safe-integer range")
    return value


def _resolve_string(node: dict[str, Any], where: str) -> dict[str, Any]:
    _check_facets(node, {"type", "format", "pattern", "max_utf8_bytes"}, where, "string")
    pattern, max_utf8_bytes, nfc_check = None, None, False
    if "format" in node:
        format_name = node["format"]
        if format_name not in ALLOWED_FORMATS:
            raise SchemaLintError(f"{where}: unknown format '{format_name}'")
        format_spec = FORMATS[format_name]
        pattern, max_utf8_bytes, nfc_check = format_spec["pattern"], format_spec["max_utf8_bytes"], format_spec["nfc_check"]
    if "pattern" in node:
        pattern = node["pattern"]
    if pattern is not None:
        _lint_pattern(pattern, where)
    if "max_utf8_bytes" in node:
        max_utf8_bytes = _lint_integer_bound(node["max_utf8_bytes"], f"{where}.max_utf8_bytes")
    return {"type": "string", "pattern": pattern, "max_utf8_bytes": max_utf8_bytes, "nfc_check": nfc_check}


def _resolve_integer(node: dict[str, Any], where: str) -> dict[str, Any]:
    _check_facets(node, {"type", "minimum", "maximum"}, where, "integer")
    minimum = _lint_integer_bound(node["minimum"], f"{where}.minimum") if "minimum" in node else None
    maximum = _lint_integer_bound(node["maximum"], f"{where}.maximum") if "maximum" in node else None
    if minimum is not None and maximum is not None and minimum > maximum:
        raise SchemaLintError(f"{where}: minimum {minimum} exceeds maximum {maximum}; no value can satisfy this node")
    return {"type": "integer", "minimum": minimum, "maximum": maximum}


def _resolve_enum(node: dict[str, Any], where: str) -> dict[str, Any]:
    _check_facets(node, {"type", "values"}, where, "enum")
    values = node.get("values")
    if not isinstance(values, list) or not values or not all(isinstance(v, str) for v in values):
        raise SchemaLintError(f"{where}: enum values must be a non-empty list of strings")
    if len(set(values)) != len(values):
        raise SchemaLintError(f"{where}: enum values must be unique")
    return {"type": "enum", "values": list(values)}


def _resolve_const(node: dict[str, Any], where: str) -> dict[str, Any]:
    _check_facets(node, {"type", "value"}, where, "const")
    value = node.get("value")
    if isinstance(value, bool) or not isinstance(value, (str, int)):
        raise SchemaLintError(f"{where}: const value must be a string or integer")
    if isinstance(value, int):
        # Beyond the safe-integer range Python keeps the constant exact while the
        # emitted JS literal rounds it, so the two runtimes would compare against
        # different numbers forever.
        _lint_integer_bound(value, f"{where}.value")
    return {"type": "const", "value": value}


def _resolve_object(node: dict[str, Any], defs: dict[str, Any], where: str, stack: tuple[str, ...]) -> dict[str, Any]:
    _check_facets(node, {"type", "required", "properties", "max_keys", "additional_properties"}, where, "object")
    properties = node.get("properties")
    if not isinstance(properties, dict):
        raise SchemaLintError(f"{where}: object requires a 'properties' map")
    required = node.get("required", [])
    if not isinstance(required, list) or not all(isinstance(r, str) for r in required):
        raise SchemaLintError(f"{where}: 'required' must be a list of field names")
    unknown_required = set(required) - set(properties.keys())
    if unknown_required:
        raise SchemaLintError(f"{where}: required field(s) {sorted(unknown_required)} not declared in properties")
    if "max_keys" not in node:
        raise SchemaLintError(f"{where}: object requires an explicit 'max_keys' facet")
    max_keys = _lint_integer_bound(node["max_keys"], f"{where}.max_keys")
    additional_properties = node.get("additional_properties", "reject")
    if additional_properties not in ALLOWED_ADDITIONAL_PROPERTIES:
        raise SchemaLintError(f"{where}: invalid additional_properties '{additional_properties}'")
    if max_keys < len(required):
        raise SchemaLintError(
            f"{where}: max_keys {max_keys} is below the {len(required)} required field(s); no value can satisfy this node"
        )
    if additional_properties == "preserve" and max_keys <= len(properties):
        # `preserve` exists to carry forward fields this version does not know
        # about. Without headroom above the declared property count, a complete
        # payload leaves no room for one, so the forward-compat promise is dead.
        raise SchemaLintError(
            f"{where}: additional_properties 'preserve' needs max_keys above the {len(properties)} declared "
            f"properties, got {max_keys}"
        )
    resolved_properties = {k: _resolve_node(v, defs, f"{where}.properties.{k}", stack) for k, v in properties.items()}
    return {
        "type": "object",
        "required": list(required),
        "properties": resolved_properties,
        "max_keys": max_keys,
        "additional_properties": additional_properties,
    }


def _resolve_array(node: dict[str, Any], defs: dict[str, Any], where: str, stack: tuple[str, ...]) -> dict[str, Any]:
    _check_facets(node, {"type", "items", "max_items", "unique_by"}, where, "array")
    if "items" not in node:
        raise SchemaLintError(f"{where}: array requires an 'items' node")
    if "max_items" not in node:
        raise SchemaLintError(f"{where}: array requires an explicit 'max_items' facet")
    max_items = _lint_integer_bound(node["max_items"], f"{where}.max_items")
    unique_by = node.get("unique_by", [])
    if not isinstance(unique_by, list) or not all(isinstance(u, str) for u in unique_by):
        raise SchemaLintError(f"{where}: 'unique_by' must be a list of field names")
    items = _resolve_node(node["items"], defs, f"{where}.items", stack)
    if unique_by:
        _lint_unique_by(unique_by, items, where)
    return {"type": "array", "items": items, "max_items": max_items, "unique_by": list(unique_by)}


def _lint_unique_by(unique_by: list[str], items: dict[str, Any], where: str) -> None:
    """Reject unique_by declarations the generated runtimes cannot honour.

    A unique_by field that is not REQUIRED on every item variant makes the
    Python runtime raise KeyError while JS silently reads `undefined`, and a
    non-scalar field would make the JSON key depend on each language's object
    key ordering. Both are cross-runtime divergences, so they fail at
    generation time rather than at validation time.
    """
    if len(set(unique_by)) != len(unique_by):
        raise SchemaLintError(f"{where}: 'unique_by' field names must be unique")
    if items["type"] == "object":
        variants = [items]
    elif items["type"] == "tagged_union":
        variants = list(items["variants"].values())
    else:
        raise SchemaLintError(f"{where}: 'unique_by' needs object or tagged_union items, not '{items['type']}'")
    for variant in variants:
        missing = sorted(field for field in unique_by if field not in variant["required"])
        if missing:
            raise SchemaLintError(f"{where}: 'unique_by' field(s) {missing} must be required on every item variant")
        for field in unique_by:
            field_type = variant["properties"][field]["type"]
            if field_type not in _UNIQUE_BY_SCALAR_TYPES:
                raise SchemaLintError(f"{where}: 'unique_by' field '{field}' must be a scalar, not '{field_type}'")


def _resolve_tagged_union(node: dict[str, Any], defs: dict[str, Any], where: str, stack: tuple[str, ...]) -> dict[str, Any]:
    _check_facets(node, {"type", "tag_field", "variants"}, where, "tagged_union")
    tag_field = node.get("tag_field")
    if not isinstance(tag_field, str) or not tag_field:
        raise SchemaLintError(f"{where}: tagged_union requires a non-empty 'tag_field'")
    variants = node.get("variants")
    if not isinstance(variants, dict) or not variants:
        raise SchemaLintError(f"{where}: tagged_union requires a non-empty 'variants' map")
    resolved_variants = {}
    for tag, variant_node in variants.items():
        resolved = _resolve_node(variant_node, defs, f"{where}.variants.{tag}", stack)
        if resolved.get("type") != "object":
            raise SchemaLintError(f"{where}.variants.{tag}: tagged_union variants must be object nodes")
        resolved_variants[tag] = resolved
    return {"type": "tagged_union", "tag_field": tag_field, "variants": resolved_variants}


def _resolve_ref(node: dict[str, Any], defs: dict[str, Any], where: str, stack: tuple[str, ...]) -> dict[str, Any]:
    _check_facets(node, {"type", "ref"}, where, "ref")
    ref_name = node.get("ref")
    if not isinstance(ref_name, str) or ref_name not in defs:
        raise SchemaLintError(f"{where}: unknown $defs reference '{ref_name}'")
    if ref_name in stack:
        raise SchemaLintError(f"{where}: cyclic $defs reference through '{ref_name}'")
    return _resolve_node(defs[ref_name], defs, f"_common.defs.{ref_name}", (*stack, ref_name))


_RESOLVERS_SIMPLE = {"string": _resolve_string, "integer": _resolve_integer, "enum": _resolve_enum, "const": _resolve_const}
_RESOLVERS_NESTED = {"object": _resolve_object, "array": _resolve_array, "tagged_union": _resolve_tagged_union, "ref": _resolve_ref}


def _resolve_node(node: Any, defs: dict[str, Any], where: str, stack: tuple[str, ...] = ()) -> dict[str, Any]:
    if not isinstance(node, dict) or "type" not in node:
        raise SchemaLintError(f"{where}: node must be an object with a 'type' facet")
    node_type = node["type"]
    if node_type not in ALLOWED_TYPES:
        raise SchemaLintError(f"{where}: unsupported type '{node_type}'")
    if node_type == "boolean":
        _check_facets(node, {"type"}, where, "boolean")
        return {"type": "boolean"}
    if node_type in _RESOLVERS_SIMPLE:
        return _RESOLVERS_SIMPLE[node_type](node, where)
    return _RESOLVERS_NESTED[node_type](node, defs, where, stack)


_COMMON_DOCUMENT_FACETS = {"contract", "contract_version", "frozen", "structure", "defs"}
_CONTRACT_DOCUMENT_FACETS = {"contract", "contract_version", "frozen", "root", "defs"}


def _lint_file_metadata(document: dict[str, Any], filename: str) -> None:
    contract = document.get("contract")
    if not isinstance(contract, str) or not contract:
        raise SchemaLintError(f"{filename}: missing 'contract' name")
    version = document.get("contract_version")
    if version not in {1, 2, 3, 4, 5, 6}:
        raise SchemaLintError(f"{filename}: 'contract_version' must be 1, 2, 3, 4, 5, or 6")
    if contract != "_common" and not contract.endswith(f"V{version}"):
        raise SchemaLintError(
            f"{filename}: contract name '{contract}' must end in V{version}"
        )
    # Both states are legal inputs. Freezing a contract must not stop it being
    # emitted — a frozen contract still needs its validator in both runtimes, and
    # the Stage 2 exit gate flips every file to frozen: true at once. Immutability
    # is enforced by check_plugin_contract_freeze.py's SHA lock, not by the
    # generator refusing to read the file.
    if not isinstance(document.get("frozen"), bool):
        raise SchemaLintError(f"{filename}: 'frozen' must be a boolean")
    allowed = _COMMON_DOCUMENT_FACETS if filename == COMMON_FILE else _CONTRACT_DOCUMENT_FACETS
    _check_facets(document, allowed, filename, "document")


def _merge_local_defs(document: dict[str, Any], common_defs: dict[str, Any], filename: str) -> dict[str, Any]:
    """Overlay a contract file's private $defs on the shared ones.

    Lanes author contract-local defs in their own file rather than editing the
    shared _common.schema.json, which would serialize every parallel lane behind
    one hot file. Shadowing a shared def is an error: two contracts silently
    disagreeing on `commit_epoch` is exactly the drift the closed vocabulary and
    the cross-runtime differ exist to prevent.
    """
    local = document.get("defs", {})
    if not isinstance(local, dict):
        raise SchemaLintError(f"{filename}: 'defs' must be a map when present")
    shadowed = sorted(set(local.keys()) & set(common_defs.keys()))
    if shadowed:
        raise SchemaLintError(f"{filename}: local defs may not shadow shared _common defs {shadowed}")
    return {**common_defs, **local}


def _load_schema_family(
    schema_dir: Path,
    budget_keys: set[str],
) -> tuple[dict[str, int], dict[str, Any]] | None:
    common_path = schema_dir / COMMON_FILE
    if not common_path.exists():
        return None
    common = json.loads(common_path.read_text(encoding="utf-8"))
    _lint_file_metadata(common, COMMON_FILE)
    defs = common.get("defs")
    if not isinstance(defs, dict):
        raise SchemaLintError(f"{schema_dir.name}/{COMMON_FILE}: missing 'defs' map")
    raw_structure = common.get("structure")
    if not isinstance(raw_structure, dict):
        raise SchemaLintError(f"{schema_dir.name}/{COMMON_FILE}: missing 'structure' budgets")
    missing_budgets = budget_keys - set(raw_structure)
    if missing_budgets:
        raise SchemaLintError(
            f"{schema_dir.name}/{COMMON_FILE}: missing structural budget(s) {sorted(missing_budgets)}"
        )
    structure = {
        key: _lint_integer_bound(
            raw_structure[key], f"{schema_dir.name}/{COMMON_FILE}.structure.{key}"
        )
        for key in budget_keys
    }
    discovered = contract_files(schema_dir)
    if not discovered:
        raise SchemaLintError(f"{schema_dir}: no contract schema files discovered")
    contracts: dict[str, Any] = {}
    for filename in discovered:
        label = f"{schema_dir.name}/{filename}"
        document = json.loads((schema_dir / filename).read_text(encoding="utf-8"))
        _lint_file_metadata(document, filename)
        if "root" not in document:
            raise SchemaLintError(f"{label}: missing 'root' node")
        contract_name = document["contract"]
        if contract_name in contracts:
            raise SchemaLintError(f"{label}: duplicate contract name '{contract_name}'")
        root = _resolve_node(
            document["root"], _merge_local_defs(document, defs, label), f"{label}.root"
        )
        if root.get("type") != "object":
            raise SchemaLintError(f"{label}: root node must be an object")
        contracts[contract_name] = {
            "contract_version": document["contract_version"],
            "root": root,
        }
    return structure, contracts


def _build_spec(schema_dirs: tuple[Path, ...] = SCHEMA_DIRS) -> dict[str, Any]:
    budget_keys = {"max_depth", "max_nodes", "max_object_keys", "max_array_items", "max_payload_utf8_bytes"}
    contracts: dict[str, Any] = {}
    structures: list[dict[str, int]] = []
    for schema_dir in schema_dirs:
        family = _load_schema_family(schema_dir, budget_keys)
        if family is None:
            continue
        structure, family_contracts = family
        structures.append(structure)
        for contract_name, contract in family_contracts.items():
            if contract_name in contracts:
                raise SchemaLintError(f"{schema_dir.name}: duplicate contract name '{contract_name}'")
            contracts[contract_name] = {**contract, "structure": structure}

    if not structures:
        raise SchemaLintError("no plugin schema directories were discovered")
    structure_resolved = {key: max(item[key] for item in structures) for key in budget_keys}

    for contract_name, contract in contracts.items():
        _lint_against_structural_budgets(contract["root"], contract["structure"], contract_name)

    return {"structure": structure_resolved, "contracts": contracts, "error_reasons": dict(sorted(ERROR_REASONS.items()))}


def _lint_against_structural_budgets(node: dict[str, Any], structure: dict[str, int], where: str) -> None:
    """Reject per-node ceilings the structural pre-pass makes unreachable.

    `_inspect_structure` runs BEFORE the schema walk and rejects any array or
    object over the shared budgets, so a contract declaring `max_items` above
    `max_array_items` advertises capacity that always fails as
    `array_budget_exceeded`. Catching it here keeps the declared limit honest.
    """
    if node["type"] == "array":
        if node["max_items"] > structure["max_array_items"]:
            raise SchemaLintError(
                f"{where}: max_items {node['max_items']} exceeds the structural max_array_items "
                f"{structure['max_array_items']}, so the excess is unreachable"
            )
        _lint_against_structural_budgets(node["items"], structure, f"{where}.items")
    elif node["type"] == "object":
        if node["max_keys"] > structure["max_object_keys"]:
            raise SchemaLintError(
                f"{where}: max_keys {node['max_keys']} exceeds the structural max_object_keys "
                f"{structure['max_object_keys']}, so the excess is unreachable"
            )
        for field, child in node["properties"].items():
            _lint_against_structural_budgets(child, structure, f"{where}.{field}")
    elif node["type"] == "tagged_union":
        for tag, variant in node["variants"].items():
            _lint_against_structural_budgets(variant, structure, f"{where}[{tag}]")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    spec = _build_spec()
    expected = {JS_PATH: js_source(copy.deepcopy(spec)), PY_PATH: python_source(copy.deepcopy(spec))}
    stale = [path for path, content in expected.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            print("Generated plugin contracts are stale:", *(str(path.relative_to(ROOT)) for path in stale))
            return 1
        print("Plugin contract generator: up to date")
        return 0
    for path, content in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
