from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parents[2]


def _load_script_module(script_path: str) -> ModuleType:
    path = ROOT / script_path
    spec = importlib.util.spec_from_file_location(
        f"phase2_{script_path.replace('/', '_')}", path
    )
    if spec is None or spec.loader is None:  # pragma: no cover - defensive guard
        raise RuntimeError(f"unable to load script module: {script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _release_workflow_yaml(*, build_preload: bool) -> str:
    """A minimal two-step release job, optionally missing the preload build.

    ``build_preload=False`` reproduces the shipped-at-the-time defect: the job
    invokes electron-builder from a clean checkout where ``preload.bundle.js``
    is gitignored, untracked, and generated by nothing.
    """
    preload_step = (
        "      - name: Build sandboxed preload bundle\n        run: npm run build:preload\n"
        if build_preload
        else ""
    )
    return (
        "name: Release\n"
        "on:\n"
        "  push:\n"
        '    tags: ["v*"]\n'
        "jobs:\n"
        "  build:\n"
        "    runs-on: windows-latest\n"
        "    steps:\n"
        "      - name: Install Node dependencies\n"
        "        run: npm ci\n"
        f"{preload_step}"
        "      - name: Build & publish installer\n"
        "        run: npm exec -- electron-builder --win --publish always\n"
    )


def _write_release_workflows(root: Path, *, build_preload: bool = True) -> None:
    for name in ("release.yml", "release-attestation.yml"):
        _write(
            root / ".github" / "workflows" / name,
            _release_workflow_yaml(build_preload=build_preload),
        )


def _write_release_policy_fixture(root: Path, *, package_version: str = "0.1.0") -> None:
    _write_release_workflows(root)
    _write(
        root / "package.json",
        (
            "{\n"
            f'  "version": "{package_version}",\n'
            '  "scripts": {\n'
            '    "build:sidecar": "python scripts/packaging/build_sidecar_artifact.py",\n'
            '    "build:restricted-host": "python scripts/packaging/build_restricted_host_artifact.py",\n'
            '    "build:restricted-host:release": "python scripts/packaging/build_restricted_host_artifact.py --release",\n'
            '    "build:full-host-supervisor": "python scripts/packaging/build_full_host_supervisor_artifact.py",\n'
            '    "build:full-host-supervisor:release": "python scripts/packaging/build_full_host_supervisor_artifact.py --release",\n'
            '    "pack:dir": "npm run build:preload && npm run check:python-runtime-bundle && npm run build:sidecar && npm run build:restricted-host && npm run build:full-host-supervisor && npm run sbom:sidecar && npm exec -- electron-builder --dir --config electron-builder.yml --publish never",\n'
            '    "pack:release": "npm run build:preload:force && npm run check:python-runtime-bundle && npm run build:sidecar && npm run build:restricted-host:release && npm run build:full-host-supervisor:release && npm run sbom:sidecar && npm exec -- electron-builder --config electron-builder.yml --publish never",\n'
            '    "release:windows": "npm run build:preload:force && npm run check:python-runtime-bundle && npm run build:sidecar && npm run build:restricted-host:release && npm run build:full-host-supervisor:release && npm run sbom:sidecar && npm exec -- electron-builder --win --config electron-builder.yml --publish always",\n'
            '    "release:smoke": "python scripts/packaging/smoke_packaged_flow.py"\n'
            "  },\n"
            '  "dependencies": {"electron-updater": "^6.6.2"}\n'
            "}\n"
        ),
    )
    _write(
        root / "pyproject.toml",
        f'[project]\nname = "companion-sidecar"\nversion = "{package_version}"\n',
    )
    _write(
        root / "package-lock.json",
        (
            "{\n"
            '  "name": "jenny",\n'
            f'  "version": "{package_version}",\n'
            '  "lockfileVersion": 3,\n'
            '  "packages": {\n'
            '    "": {\n'
            '      "name": "jenny",\n'
            f'      "version": "{package_version}"\n'
            "    }\n"
            "  }\n"
            "}\n"
        ),
    )
    _write(
        root / "services" / "backend" / "managed-sidecar-lifecycle.js",
        "const config = { clientVersion: service.appVersion };\n",
    )
    _write(
        root / "scripts" / "packaging" / "emit_sbom.py",
        'component = {"name": "companion-sidecar", "version": package_version}\n',
    )
    _write(
        root / "sidecar" / "runtime" / "diagnostics.py",
        "SCHEMA_VERSION = 1\n",
    )
    _write(
        root / "sidecar" / "runtime" / "capabilities.py",
        (
            f'SERVER_VERSION = "{package_version}"\n'
            'payload = {"schema_version": 1, "server_version": SERVER_VERSION}\n'
        ),
    )
    _write(
        root / "RELEASE_NOTES.md",
        (
            "# Release Notes\n\n"
            f"## {package_version} - Unreleased\n\n"
            "### App\n\n- Baseline.\n\n"
            "<!-- JENNY_RELEASE_SHA256_MANIFEST_START -->\n"
            "| File | SHA256 |\n"
            "| --- | --- |\n"
            "| Jenny.exe | "
            "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef |\n"
            "<!-- JENNY_RELEASE_SHA256_MANIFEST_END -->\n"
        ),
    )


def test_release_manifest_block_check_detects_missing_block(tmp_path) -> None:
    module = _load_script_module("scripts/checks/check_release_manifest_block.py")
    _write(tmp_path / "RELEASE_NOTES.md", "# Release Notes\n\nNo manifest here.\n")

    violations = module.validate_release_manifest_block(tmp_path)

    assert violations == ["RELEASE_NOTES.md missing SHA256 manifest block"]


def test_release_manifest_block_builds_release_body_block(tmp_path) -> None:
    module = _load_script_module("scripts/checks/release_manifest_block.py")
    asset = tmp_path / "dist" / "Jenny.exe"
    _write(asset, "installer bytes")

    block = module.build_manifest_block([asset], root=tmp_path)

    digest = hashlib.sha256(b"installer bytes").hexdigest()
    assert "| dist/Jenny.exe |" in block
    assert digest in block
    assert module.validate_manifest_block(
        block,
        require_assets=True,
        root=tmp_path,
        verify_assets=True,
    ) == []


def test_release_manifest_block_rejects_duplicate_and_misordered_markers() -> None:
    module = _load_script_module("scripts/checks/release_manifest_block.py")
    digest = "a" * 64
    block = (
        f"{module.MANIFEST_START}\n"
        "| File | SHA256 |\n"
        "| --- | --- |\n"
        f"| dist/Jenny.exe | {digest} |\n"
        f"{module.MANIFEST_END}\n"
    )

    assert module.validate_manifest_block(block + block, require_assets=True) == [
        "SHA256 manifest block must contain exactly one start marker and one end marker"
    ]
    assert module.validate_manifest_block(
        f"{module.MANIFEST_END}\n{module.MANIFEST_START}\n"
    ) == ["SHA256 manifest block markers are misordered"]
    with pytest.raises(ValueError, match="exactly one start marker"):
        module.replace_manifest_block(block + block, block)


def test_release_manifest_block_check_detects_stale_asset_hash(tmp_path) -> None:
    module = _load_script_module("scripts/checks/check_release_manifest_block.py")
    asset = tmp_path / "dist" / "Jenny.exe"
    _write(asset, "current installer bytes")
    stale_digest = hashlib.sha256(b"old installer bytes").hexdigest()
    _write(
        tmp_path / "RELEASE_NOTES.md",
        (
            "# Release Notes\n\n"
            "<!-- JENNY_RELEASE_SHA256_MANIFEST_START -->\n"
            "| File | SHA256 |\n"
            "| --- | --- |\n"
            f"| dist/Jenny.exe | {stale_digest} |\n"
            "<!-- JENNY_RELEASE_SHA256_MANIFEST_END -->\n"
        ),
    )

    violations = module.validate_release_manifest_block(
        tmp_path,
        require_assets=True,
    )

    assert violations == ["SHA256 mismatch for release asset: dist/Jenny.exe"]


def test_release_manifest_block_rejects_assets_outside_root(tmp_path) -> None:
    module = _load_script_module("scripts/checks/release_manifest_block.py")
    asset = tmp_path.parent / "outside-installer.exe"
    _write(asset, "outside installer bytes")

    try:
        with pytest.raises(RuntimeError, match="outside the release root"):
            module.build_manifest_block([asset], root=tmp_path)
    finally:
        asset.unlink(missing_ok=True)


def test_live_local_evidence_attributes_failure_to_executing_phase(
    tmp_path, monkeypatch
) -> None:
    module = _load_script_module("scripts/tests/live-local-evidence.py")
    output = tmp_path / "evidence.json"
    reliability_calls = 0

    def run_reliability_model(**_kwargs):
        nonlocal reliability_calls
        reliability_calls += 1
        if reliability_calls == 2:
            raise RuntimeError("second Ollama gate failed")
        return {"status": "passed"}

    monkeypatch.setattr(module, "_git_revision", lambda: "test-revision")
    monkeypatch.setattr(module, "run_reliability_model", run_reliability_model)

    result = module.main(
        [
            "--phase",
            "ollama",
            "--phase",
            "vllm",
            "--tool-cases",
            "1",
            "--control-cases",
            "0",
            "--output",
            str(output),
        ]
    )
    evidence = json.loads(output.read_text(encoding="utf-8"))

    assert result == 1
    assert evidence["failure"] == {
        "error_type": "RuntimeError",
        "stage": "ollama",
    }


def test_release_version_policy_accepts_aligned_fixture(tmp_path) -> None:
    module = _load_script_module("scripts/checks/check_release_version_policy.py")
    _write_release_policy_fixture(tmp_path)

    violations = module.validate_release_version_policy(tmp_path)

    assert violations == []


def test_release_version_policy_detects_client_version_drift(tmp_path) -> None:
    module = _load_script_module("scripts/checks/check_release_version_policy.py")
    _write_release_policy_fixture(tmp_path, package_version="0.1.0")
    _write(
        tmp_path / "services" / "backend" / "managed-sidecar-lifecycle.js",
        "const config = { clientVersion: '9.9.9' };\n",
    )

    violations = module.validate_release_version_policy(tmp_path)

    assert any("clientVersion" in violation for violation in violations)


def test_release_version_policy_detects_sidecar_server_version_drift(tmp_path) -> None:
    module = _load_script_module("scripts/checks/check_release_version_policy.py")
    _write_release_policy_fixture(tmp_path, package_version="0.2.0")
    _write(
        tmp_path / "sidecar" / "runtime" / "capabilities.py",
        'SERVER_VERSION = "0.1.0"\npayload = {"server_version": SERVER_VERSION}\n',
    )

    violations = module.validate_release_version_policy(tmp_path)

    assert any("SERVER_VERSION" in violation for violation in violations)


def test_release_workflow_missing_preload_build_is_rejected(tmp_path) -> None:
    """A workflow that packages without building the gitignored preload fails.

    Regression for the release blocker: both workflows invoked electron-builder
    directly, so a clean-checkout tag build shipped an asar with no preload and
    a window whose ``jennyShell`` bridge was undefined -- while the build itself
    reported success and published.
    """
    module = _load_script_module("scripts/checks/check_release_version_policy.py")
    _write_release_policy_fixture(tmp_path)
    _write_release_workflows(tmp_path, build_preload=False)

    violations = module.validate_release_version_policy(tmp_path)

    offenders = [v for v in violations if "electron-builder" in v]
    assert len(offenders) == 2, violations
    assert all("build:preload" in violation for violation in offenders)


def test_release_workflow_accepts_embedded_preload_npm_script(tmp_path) -> None:
    """``npm run release:windows`` already embeds the preload build."""
    module = _load_script_module("scripts/checks/check_release_version_policy.py")
    _write_release_policy_fixture(tmp_path)
    for name in ("release.yml", "release-attestation.yml"):
        _write(
            tmp_path / ".github" / "workflows" / name,
            (
                "name: Release\n"
                "on:\n"
                "  push:\n"
                '    tags: ["v*"]\n'
                "jobs:\n"
                "  build:\n"
                "    runs-on: windows-latest\n"
                "    steps:\n"
                "      - name: Build & publish\n"
                "        run: npm run release:windows\n"
            ),
        )

    violations = module.validate_release_version_policy(tmp_path)

    assert violations == []


def test_release_workflow_preload_must_precede_electron_builder(tmp_path) -> None:
    """Ordering matters: building the preload after packaging is still broken."""
    module = _load_script_module("scripts/checks/check_release_version_policy.py")
    _write_release_policy_fixture(tmp_path)
    _write(
        tmp_path / ".github" / "workflows" / "release.yml",
        (
            "name: Release\n"
            "on:\n"
            "  push:\n"
            '    tags: ["v*"]\n'
            "jobs:\n"
            "  build:\n"
            "    runs-on: windows-latest\n"
            "    steps:\n"
            "      - name: Build & publish installer\n"
            "        run: npm exec -- electron-builder --win --publish always\n"
            "      - name: Build sandboxed preload bundle\n"
            "        run: npm run build:preload\n"
        ),
    )

    violations = module.validate_release_version_policy(tmp_path)

    assert any("release.yml" in v and "electron-builder" in v for v in violations)
